"""Generate a PRISMA 2020 flow PNG and DOCX report from a screening manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from PIL import Image, ImageDraw, ImageFont


def font(size: int, bold: bool = False):
    candidates = [Path("C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf"), Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


def box(draw: ImageDraw.ImageDraw, xy: tuple[int, int, int, int], title: str, count: int, fill: str = "white") -> None:
    draw.rounded_rectangle(xy, radius=14, fill=fill, outline="#cfd2d8", width=2)
    x1, y1, x2, _ = xy
    draw.text(((x1+x2)/2, y1+26), title, fill="#17212c", anchor="mm", font=font(22, True))
    draw.text(((x1+x2)/2, y1+62), f"n = {count}", fill="#4f5863", anchor="mm", font=font(20))


def export(manifest_path: Path, output_dir: Path) -> None:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    screened, included, excluded, review = data["records"], data["included"], data["excluded"], data["needs_review"]
    identified = int(data.get("identified", screened + int(data.get("duplicates_removed", 0))))
    duplicates = identified - screened
    image = Image.new("RGB", (1400, 1850), "#f8f8f6")
    draw = ImageDraw.Draw(image)
    draw.text((700, 60), "PRISMA 2020 flow diagram", fill="#17212c", anchor="mm", font=font(36, True))
    stages = [("IDENTIFICATION", 190), ("SCREENING", 670), ("INCLUDED", 1360)]
    for label, y in stages:
        draw.text((75, y), label, fill="#6f63d9", anchor="mm", font=font(16, True))
    box(draw, (250, 150, 1150, 260), "Records identified from databases", identified)
    box(draw, (790, 350, 1270, 460), "Duplicate records removed", duplicates, "#f1f2f3")
    draw.line((700, 260, 700, 620), fill="#8882c9", width=4)
    draw.polygon([(688, 606), (712, 606), (700, 624)], fill="#8882c9")
    box(draw, (250, 640, 1150, 750), "Records screened", screened)
    box(draw, (790, 830, 1270, 940), "Records excluded", excluded, "#fff0ed")
    draw.line((700, 750, 700, 1080), fill="#8882c9", width=4)
    box(draw, (250, 1100, 1150, 1210), "Reports assessed for eligibility", included + review)
    box(draw, (790, 1280, 1270, 1390), "Awaiting reviewer adjudication", review, "#fff3da")
    draw.line((700, 1210, 700, 1480), fill="#8882c9", width=4)
    draw.polygon([(688, 1466), (712, 1466), (700, 1484)], fill="#8882c9")
    box(draw, (250, 1500, 1150, 1620), "Studies included in review", included, "#efedff")
    draw.text((700, 1730), f"Generated by Lattice · criteria {data.get('criteria_hash','')[:12]} · manifest {data.get('manifest_hash','')[:12]}", fill="#727b85", anchor="mm", font=font(15))
    output_dir.mkdir(parents=True, exist_ok=True)
    png = output_dir / "prisma_flow.png"
    image.save(png)

    document = Document()
    title = document.add_heading("PRISMA 2020 screening report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph = document.add_paragraph("Automatically generated from a versioned Lattice screening manifest. Counts should be adjudicated and signed off by the review team before publication.")
    paragraph.style.font.size = Pt(10)
    document.add_picture(str(png), width=Inches(6.3))
    document.add_heading("Screening summary", level=1)
    table = document.add_table(rows=1, cols=2)
    table.style = "Light Shading Accent 1"
    table.rows[0].cells[0].text, table.rows[0].cells[1].text = "Stage", "Records"
    for label, value in [("Identified", identified), ("Duplicates removed", duplicates), ("Screened", screened), ("Excluded", excluded), ("Awaiting adjudication", review), ("Included", included)]:
        cells = table.add_row().cells
        cells[0].text, cells[1].text = label, str(value)
    document.add_heading("Reproducibility", level=1)
    document.add_paragraph(f"Criteria hash: {data.get('criteria_hash', 'not recorded')}\nManifest hash: {data.get('manifest_hash', 'not recorded')}")
    document.save(output_dir / "prisma_report.docx")


if __name__ == "__main__":
    cli = argparse.ArgumentParser()
    cli.add_argument("manifest")
    cli.add_argument("--output", default="outputs/slr_run")
    args = cli.parse_args()
    export(Path(args.manifest), Path(args.output))
